DynConSurveys/Models/AvailableSurveyModel.cs
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynConSurveys.Models
{
    public class AvailableSurveyModel
    {
        public AvailableSurveyModel()
        {
            Definitions.Add(new SurveyDefinitionModel(1, "Survey A"));
            Definitions.Add(new SurveyDefinitionModel(2, "Survey B"));
            Definitions.Add(new SurveyDefinitionModel(3, "Survey C"));
            Definitions.Add(new SurveyDefinitionModel(4, "Survey D"));
        }

        internal SurveyDefinitionModel FindById(int id)
        {
            foreach (var definition in Definitions)
            {
                if (definition.Id == id)
                    return definition;
            }
            return null;
        }

        public List<SurveyDefinitionModel> Definitions { get; } = new List<SurveyDefinitionModel>();
    }
}

DynConSurveys/Models/ErrorViewModel.cs
using System;

namespace DynConSurveys.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

DynConSurveys/Models/QuestionBaseModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynConSurveys.Models
{
    public abstract class QuestionBaseModel
    {
        public string Question { get; set; }

        public abstract string QuestionType { get; }
    }
}

DynConSurveys/Models/QuestionMultipleCheckBoxModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynConSurveys.Models
{
    public class QuestionMultipleCheckBoxModel : QuestionMultipleChoiceModel
    {
        public override string QuestionType => "QuestionMultipleCheckBox";

        public bool Choice_A { get; set; }
        public bool Choice_B { get; set; }
        public bool Choice_C { get; set; }
        public bool Choice_D { get; set; }
    }
}

DynConSurveys/Models/QuestionMultipleChoiceModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynConSurveys.Models
{
    public class ChoiceList
    {
        public string this[string index]
        {
            get { return "You want an " + index; }
        }
    }

    public abstract class QuestionMultipleChoiceModel : QuestionBaseModel
    {

        public ChoiceList Choices { get; } = new ChoiceList();

     }
}

DynConSurveys/Models/QuestionMultipleRadioModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynConSurveys.Models
{
    public class QuestionMultipleRadioModel : QuestionMultipleChoiceModel
    {
        public override string QuestionType => "QuestionMultipleRadio";

        public string Selection { get; set; }
    }
}

DynConSurveys/Models/QuestionTextFieldModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace DynConSurveys.Models
{
    public class QuestionTextFieldModel : QuestionBaseModel
    {
        public string Answer { get; set; }

        public override string QuestionType => "QuestionTextFieldModel";
    }
}

DynConSurveys/Models/SurveyDefinitionModel.cs
using System;
using System.Collections.Generic;

namespace DynConSurveys.Models
{
    public class SurveyDefinitionModel
    {
        public SurveyDefinitionModel()
        { }


        public SurveyDefinitionModel(int id, string title)
        {
            Id = id;
            Title = title;
            Questions.Add(new QuestionMultipleRadioModel());
            Questions.Add(new QuestionMultipleRadioModel());
            Questions.Add(new QuestionMultipleCheckBoxModel());
            Questions.Add(new QuestionMultipleCheckBoxModel());
        }
        public int Id { get; set; }
        public String Title { get; set; }
        public List<QuestionBaseModel> Questions { get; set; } = new List<QuestionBaseModel>();

    }
}

DynConSurveys/Controllers/SurveySelectionController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using DynConSurveys.Models;

namespace DynConSurveys.Controllers
{
    public class SurveySelectionController : Controller
    {
        public IActionResult Index()
        {
            var model = new AvailableSurveyModel();
            return View(model);
        }

        public IActionResult SelectSurvey(int id)
        {
            if (Request.Method == "POST")
            {
                return null;
            }
            var model = new AvailableSurveyModel();
            var definition = model.FindById(id);
            return View("SurveyEntry", definition);
        }
        public void OnPost()
        {
            var f = Request.Form;
            // do something with emailAddress
        }

        [HttpPost]
        public IActionResult SurveyPostback(int id, SurveyDefinitionModel definition)
        {
            return View("SurveyEntry", definition);
        }
        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

DynConSurveys/Views/Originals/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div id="myCarousel" class="carousel slide" data-ride="carousel" data-interval="6000">
    <ol class="carousel-indicators">
        <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
        <li data-target="#myCarousel" data-slide-to="1"></li>
        <li data-target="#myCarousel" data-slide-to="2"></li>
    </ol>
    <div class="carousel-inner" role="listbox">
        <div class="item active">
            <img src="~/images/banner1.svg" alt="ASP.NET" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how to build ASP.NET apps that can run anywhere.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525028&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner2.svg" alt="Visual Studio" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    There are powerful new features in Visual Studio for building modern web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525030&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
        <div class="item">
            <img src="~/images/banner3.svg" alt="Microsoft Azure" class="img-responsive" />
            <div class="carousel-caption" role="option">
                <p>
                    Learn how Microsoft's Azure cloud platform allows you to build, deploy, and scale web apps.
                    <a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkID=525027&clcid=0x409">
                        Learn More
                    </a>
                </p>
            </div>
        </div>
    </div>
    <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
    </a>
</div>

<div class="row">
    <div class="col-md-3">
        <h2>Application uses</h2>
        <ul>
            <li>Sample pages using ASP.NET Core MVC</li>
            <li>Theming using <a href="https://go.microsoft.com/fwlink/?LinkID=398939">Bootstrap</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>How to</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398600">Add a Controller and View</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699315">Manage User Secrets using Secret Manager.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699316">Use logging to log a message.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699317">Add packages using NuGet.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699319">Target development, staging or production environment.</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Overview</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=518008">Conceptual overview of what is ASP.NET Core</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=699320">Fundamentals of ASP.NET Core such as Startup and middleware.</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398602">Working with Data</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkId=398603">Security</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699321">Client side development</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699322">Develop on different platforms</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=699323">Read more on the documentation site</a></li>
        </ul>
    </div>
    <div class="col-md-3">
        <h2>Run &amp; Deploy</h2>
        <ul>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517851">Run your app</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=517853">Run tools such as EF migrations and more</a></li>
            <li><a href="https://go.microsoft.com/fwlink/?LinkID=398609">Publish to Microsoft Azure Web Apps</a></li>
        </ul>
    </div>
</div>

DynConSurveys/Views/Shared/EditorTemplates/QuestionMultipleCheckBoxModel.cshtml

@model QuestionMultipleCheckBoxModel

@Html.Hidden("ModelType", Model.GetType())

<h3>@Html.LabelFor(m => m.Question)</h3>
<br>
@Html.CheckBoxFor(m => m.Choice_A) @Model.Choices["A"]
<br>
@Html.CheckBoxFor(m => m.Choice_B) @Model.Choices["B"]
<br>
@Html.CheckBoxFor(m => m.Choice_C) @Model.Choices["C"]
<br>
@Html.CheckBoxFor(m => m.Choice_D) @Model.Choices["D"]


DynConSurveys/Views/Shared/EditorTemplates/QuestionMultipleRadioModel.cshtml

@model QuestionMultipleRadioModel

@Html.Hidden("ModelType", Model.GetType())

<h3>@Html.LabelFor(m => m.Question)</h3>
<br>
@Html.RadioButtonFor(m => m.Selection, "A") @Model.Choices["A"]
<br>
@Html.RadioButtonFor(m => m.Selection, "B") @Model.Choices["B"]
<br>
@Html.RadioButtonFor(m => m.Selection, "C") @Model.Choices["C"]
<br>
@Html.RadioButtonFor(m => m.Selection, "D") @Model.Choices["D"]


DynConSurveys/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - DynConSurveys</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="SurveySelection" asp-action="Index" class="navbar-brand">DynConSurveys</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="SurveySelection" asp-action="Index">Survey Selection</a></li>
                    <li><a asp-area="" asp-controller="SurveySelection" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="SurveySelection" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - DynConSurveys</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/3.4.1/js/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-aJ21OjlMXNL5UyIl/XNwTMqvzeRMZH2w8c5cRVpzpU8Y5bApTppSuUkhZXN0VxHd">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>

DynConSurveys/Views/SurveySelection/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

DynConSurveys/Views/SurveySelection/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

DynConSurveys/Views/SurveySelection/Index.cshtml
@{
    ViewData["Title"] = "Select Desired Survey";
}

    <div>
        <h2>Select Desired Survey</h2>
        <br />
        <br />
        @foreach (var definition in Model.Definitions)
        {
            <a asp-area="" asp-controller="SurveySelection" asp-action="SelectSurvey" asp-route-id="@definition.Id">@definition.Title</a>
        <br />
        }
    </div>

DynConSurveys/Views/SurveySelection/QuestionMultipleCheckBox.cshtml

@model QuestionMultipleCheckBoxModel

<h3>@Html.LabelFor(m=>m.Question)</h3>
<br>
@Html.CheckBoxFor(m => m.Choice_A) @Model.Choices["A"]
<br>
@Html.CheckBoxFor(m => m.Choice_B) @Model.Choices["B"]
<br>
@Html.CheckBoxFor(m => m.Choice_C) @Model.Choices["C"]
<br>
@Html.CheckBoxFor(m => m.Choice_D) @Model.Choices["D"]


DynConSurveys/Views/SurveySelection/QuestionMultipleRadio.cshtml
@*
    For more information on enabling MVC for empty projects, visit http://go.microsoft.com/fwlink/?LinkID=397860
*@
<h3>@Model.Question</h3>
<input type="radio" name="selection" value="A"> @Model.Choices["A"]
<br>
<input type="radio" name="selection" value="B"> @Model.Choices["B"]
<br>
<input type="radio" name="selection" value="C"> @Model.Choices["C"]
<br>
<input type="radio" name="selection" value="D"> @Model.Choices["D"]


DynConSurveys/Views/SurveySelection/SurveyEntry.cshtml

@model SurveyDefinitionModel
@{
    ViewData["Title"] = "Please Complete Survey";
}


    <div>
        <h2>@Model.Title</h2>
        <br />
        <br />
        @using (Html.BeginForm("SurveyPostback", "SurveySelection", FormMethod.Post, new { @area = "", @role = "form" }))
        {
            @Html.HiddenFor(m => m.Id)
            @Html.HiddenFor(m => m.Title)
            @Html.EditorFor(m=>m.Questions);

            @*@foreach (var question in Model.Questions)
            {
                Html.EditorFor(m=>question,question.QuestionType+"Model");
                <partial name="@question.QuestionType" model='@question' />
            }*@
            <br />
            <br />
            <input type="submit" value="Submit Survey">
        }
    </div>